advanced:
  clear_cache: true
  deterministic: false
  low_memory_mode: false
  normalize_images: false
  random_seed: 42
  remove_outliers: false
analysis:
  explained_variance_threshold: 0.95
  metric: euclidean
  min_dist: 0.01
  n_neighbors: 15
  pca_components: 50
  umap_components: 2
cluster:
  conda_env: merenv
  cpu_job:
    cpus_per_task: 16
    mem: 128G
    nodes: 1
    partition: cpu
    time: '2:00:00'
  gpu_job:
    cpus_per_task: 8
    gres: gpu:1
    mem: 64G
    nodes: 1
    partition: gpu
    time: '4:00:00'
  modules:
  - anaconda3/2023.9
  scratch_base: /scratch/gpfs
  use_scratch: true
data:
  input_path: ../../local_data/pieridae_output
  output_path: ../../local_data/byol_results
inference: 
  batch_size: 1024
labels:  
  classifications_file: ./classifications_kadofong_20250926.csv
  index_column: 0
  label_mapping:
    0: unclassified
    1: undisturbed
    2: ambiguous
    3: merger
    4: fragmentation
    5: artifact
logging:
  console_output: true
  level: INFO
  save_logs: true
model:
  image_size: 150
  moving_average_decay: 0.99
  projection_hidden_size: 1024
  projection_size: 128
training:
  batch_size: 1024
  learning_rate: 0.0003
  num_epochs: 300
  resume: true
  save_interval: 100
visualization:
  create_plots: true
  dpi: 300
  figsize:
  - 12
  - 8
  plot_format: png
