#!/usr/bin/env python3
"""
Generate Punchline Figures for Merger Analysis

This script creates all publication-quality figures from the merger classification
analysis, converting the exploratory notebook analysis into reproducible figure generation.

Features:
- Loads BYOL embeddings, PCA reductions, and label propagations
- Generates 9 key figures showing merger classifications and relationships
- Clean separation between data loading and figure generation
- Each figure is generated by its own function for readability

Usage:
    # Generate all figures using default config
    python make_punchlines.py

    # Specify custom config
    python make_punchlines.py --config ../custom_config.yaml

    # Specify output directory
    python make_punchlines.py --output-dir ../figures/

    # Generate only specific figures
    python make_punchlines.py --figures 1,2,3
"""

import os
import sys
import argparse
import logging
import pickle
import glob
from pathlib import Path
from typing import Dict, Tuple, Optional

import yaml
import numpy as np
from scipy import stats
import pandas as pd
import torch
import matplotlib
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib import colors
from scipy.stats import gaussian_kde
from tqdm import tqdm

# Add pieridae to path
sys.path.insert(0, str(Path(__file__).parents[2]))

from pieridae.starbursts.byol import (
    EmbeddingAnalyzer,
    LabelPropagation,
    FrozenClassifier,
)
from pieridae.starbursts import sample
from ekfplot import plot as ek, colors as ec, colorlists
from ekfphys import calibrations
from ekfstats import sampling

cmap = ec.colormap_from_list([
    ec.ColorBase(colorlists.slides['orange']).modulate(-0.3,-0.1).base, 
    colorlists.slides['orange'], 
    plt.cm.coolwarm(0.5), 
    colorlists.slides['bluebird'],
    ec.ColorBase(colorlists.slides['bluebird']).modulate(0.3,0.3).base, 
])


def setup_logging(level: str = 'INFO') -> logging.Logger:
    """Setup logging configuration"""
    logger = logging.getLogger('make_punchlines')
    logger.setLevel(getattr(logging, level))

    formatter = logging.Formatter(
        '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)

    return logger


def load_config(config_path: str, input_path: Optional[str] = None) -> dict:
    """Load configuration from YAML file"""
    with open(config_path, 'r') as f:
        config = yaml.safe_load(f)

    config['data']['input_path'] = Path(config['data']['input_path'])
    config['data']['output_path'] = Path(config['data']['output_path'])

    # Override output_path if provided via command line
    if input_path is not None:
        config['data']['output_path'] = Path(input_path)
    #Path('../output/fiducial/')

    return config


def load_image_by_name(img_name: str, data_path: Path) -> np.ndarray:
    """
    Load a single galaxy image on-demand.

    Parameters
    ----------
    img_name : str
        Galaxy ID (e.g., 'M1234567890123456789')
    data_path : Path
        Base data directory path

    Returns
    -------
    image : np.ndarray
        Image array with shape (3, H, W) containing [g-band, i-band, hf_i-band]
    """
    i_file = data_path / img_name / f"{img_name}_i_results.pkl"
    g_file = data_path / img_name / f"{img_name}_g_results.pkl"

    img = []
    for band_file in [g_file, i_file]:
        with open(band_file, 'rb') as f:
            xf = pickle.load(f)
            img.append(xf['image'])
            if band_file == i_file:
                img.append(xf['hf_image'])

    return np.array(img, dtype=np.float32)


def load_data(config: dict, logger: logging.Logger,
              use_nn_classifier: bool = True, 
              force_pca_load: bool = False,
              update_masses=False,
              mass_cachefile = Path(os.environ['HOME']) / '.cache/merian/logmass_adjusted.csv'
              ) -> Dict:
    """
    Load all data needed for figure generation.

    This function consolidates all data loading operations from the notebook
    into a single place, including:
    - Embeddings and PCA reduction
    - Image names and labels
    - Label propagation results
    - Full catalog with adjusted masses
    - H-alpha morphology statistics
    - Satellite classifications

    Parameters
    ----------
    config : dict
        Configuration dictionary
    logger : logging.Logger
        Logger instance

    Returns
    -------
    data : dict
        Dictionary containing all loaded data
    """
    logger.info("=" * 60)
    logger.info("LOADING DATA")
    logger.info("=" * 60)

    data = {}

    # Get paths
    data_path = config['data']['input_path']
    output_path = config['data']['output_path']

    logger.info(f"Input path: {data_path}")
    logger.info(f"Output path: {output_path}")

    # Load image names
    logger.info("Loading image names...")
    pattern = f"{data_path}/M*/*i_results.pkl"
    filenames = glob.glob(pattern)

    valid_files = []
    for fname in filenames:
        g_file = fname.replace('_i_', '_g_')
        i_file = fname
        if os.path.exists(g_file) and os.path.exists(i_file):
            valid_files.append(fname)

    img_names = np.array([Path(fname).parent.name for fname in valid_files])
    data['img_names'] = img_names
    data['data_path'] = data_path
    logger.info(f"Found {len(img_names)} images")

    # Load embeddings
    logger.info("Loading embeddings...")
    embeddings_file = output_path / 'embeddings.npy'
    if not embeddings_file.exists():
        raise FileNotFoundError(f"Embeddings not found: {embeddings_file}")

    embeddings = np.load(embeddings_file)
    data['embeddings'] = embeddings
    logger.info(f"Embeddings shape: {embeddings.shape}")

    if (not use_nn_classifier) or force_pca_load:
        # Compute PCA
        logger.info("Computing PCA...")
        analyzer = EmbeddingAnalyzer(config)
        embeddings_pca = analyzer.compute_pca(embeddings)
        data['embeddings_pca'] = embeddings_pca
        explained_var = analyzer.pca.explained_variance_ratio_.sum() * 100
        logger.info(f"PCA complete: {analyzer.pca.n_components_} components, {explained_var:.1f}% variance")

    # Load labels
    logger.info("Loading classification labels...")
    label_file = Path(config.get('labels', {}).get('classifications_file', ''))

    if label_file.exists():
        mergers = pd.read_csv(label_file, index_col=0)
        labels = mergers.reindex(img_names)
        labels = labels.replace(np.nan, 0).values.flatten().astype(int)
        data['labels'] = labels

        label_meanings = config.get('labels', {}).get('label_mapping', {})
        data['label_meanings'] = label_meanings
        unique, counts = np.unique(labels, return_counts=True)

        logger.info("Label distribution:")
        for label_val, count in zip(unique, counts):
            meaning = label_meanings.get(label_val, f"unknown_{label_val}")
            logger.info(f"  {label_val} ({meaning}): {count} objects")
    else:
        logger.warning(f"Label file not found: {label_file}")
        labels = np.zeros(len(img_names), dtype=int)
        data['labels'] = labels
        data['label_meanings'] = {0: 'unclassified'}

    # Check if trained classifier is available
    logger.info("Checking for trained classifier...")
    model_path = Path(output_path) / 'byol_final_model.pt'
    

    if (model_path.exists()) and use_nn_classifier:
        try:
            checkpoint = torch.load(model_path, map_location='cpu', weights_only=False)
            if 'classifier_state_dict' in checkpoint:
                use_nn_classifier = True
                logger.info("Found trained classifier - using FrozenClassifier (neural network)")
        except Exception as e:
            logger.warning(f"Failed to load checkpoint: {e}")
            logger.info("Falling back to LabelPropagation")
            use_nn_classifier = False
        

    # Initialize appropriate classifier
    if use_nn_classifier:
        propagator = FrozenClassifier(
            model_path=model_path,
            config=config,
            logger=logger
        )
        # FrozenClassifier uses raw embeddings, not PCA
        input_embeddings = embeddings
    else:
        logger.info("Using LabelPropagation (K-NN based)")
        n_neighbors = config.get('labels', {}).get('n_neighbors', 50)
        n_min = config.get('labels', {}).get('minimum_labeled_neighbors', 5)
        n_min_auto = config.get('labels', {}).get('minimum_labeled_neighbors_for_autoprop', 10)

        propagator = LabelPropagation(
            n_neighbors=n_neighbors,
            n_min=n_min,
            n_min_auto=n_min_auto,
            prob_threshold=config.get('labels', {}).get('prob_threshold', 0.7),
            frag_threshold=config.get('labels', {}).get('frag_threshold', 0.25),
        )
        # LabelPropagation uses PCA embeddings
        input_embeddings = embeddings_pca

    # Run classification
    logger.info("Running classification...")
    iterative_labels, n_labels_iter, prob_labels_iter, stats = \
        propagator.iterative_propagation(input_embeddings, labels)

    data['iterative_labels'] = iterative_labels
    data['n_labels_iter'] = n_labels_iter
    data['prob_labels_iter'] = prob_labels_iter

    logger.info(f"Human labels: {stats['n_human']}")
    logger.info(f"Auto-labels added: {stats['n_added_iteration']}")
    logger.info(f"Total labels: {stats['n_final_auto']}")

    # Identify merger candidates
    logger.info("Identifying merger candidates...")
    fragmented = prob_labels_iter[:, 4] > 0.2
    pmerger = prob_labels_iter[:, 2] + prob_labels_iter[:, 3]
    possible_merger = pmerger > prob_labels_iter[:, 1]

    is_merger = possible_merger & ~fragmented
    is_undisturbed = ~possible_merger & ~fragmented

    data['fragmented'] = fragmented
    data['pmerger'] = pmerger
    data['possible_merger'] = possible_merger
    data['is_merger'] = is_merger
    data['is_undisturbed'] = is_undisturbed

    logger.info(f"Fragmented objects: {fragmented.sum()}")
    logger.info(f"Merger candidates: {is_merger.sum()}")

    # Load full catalog
    logger.info("Loading full catalog...")
    full_catalog, masks = sample.load_sample(
        '/Users/kadofong/work/projects/merian/local_data/base_catalogs/mdr1_n708maglt26_and_pzgteq0p1.parquet'
    )
    base_catalog = full_catalog.loc[masks['is_good'][0]]

    # Load adjusted masses
    print(mass_cachefile)
    assert os.path.exists(mass_cachefile)
    cache_exists = os.path.exists(mass_cachefile)
    if cache_exists:
        logger.info('Loading cached masses...')
        logmstar_cache = pd.read_csv(mass_cachefile, index_col=0)    
    else:
        logmstar_cache = []
       
    if update_masses or (not cache_exists) or (len(logmstar_cache) != len(base_catalog)):
        logger.info("Loading adjusted masses from individual files...")
        for sid in tqdm(base_catalog.index, desc="Loading masses"):
            filename = f'{data_path}/{sid}/{sid}_i_results.pkl'
            if not os.path.exists(filename):
                continue
            with open(filename, 'rb') as f:
                x = pickle.load(f)
            base_catalog.loc[sid, 'logmass_adjusted'] = x['logmass_adjusted']

        base_catalog.loc[base_catalog['logmass_adjusted'].isna(), 'logmass_adjusted'] = \
            base_catalog.loc[base_catalog['logmass_adjusted'].isna(), 'logmass']   
        base_catalog['logmass_adjusted'].to_csv(mass_cachefile)
    else:
        logger.info("Using cached adjusted masses...")
        base_catalog.loc[logmstar_cache.index, 'logmass_adjusted'] = logmstar_cache['logmass_adjusted']

    # Create catalog subset
    fragmented_highthresh = prob_labels_iter[:, 4] > 0.5
    catalog = base_catalog.reindex(img_names[~fragmented_highthresh])
    catalog['p_merger'] = np.where(
        (prob_labels_iter[~fragmented_highthresh] == 0).all(axis=1),
        np.nan,
        prob_labels_iter[~fragmented_highthresh, 3]
    )
    catalog['p_ambig'] = np.where(
        (prob_labels_iter[~fragmented_highthresh] == 0).all(axis=1),
        np.nan,
        prob_labels_iter[~fragmented_highthresh, 2]
    )
    catalog['p_undisturbed'] = np.where(
        (prob_labels_iter[~fragmented_highthresh] == 0).all(axis=1),
        np.nan,
        prob_labels_iter[~fragmented_highthresh, 1]
    )

    dm = catalog['logmass_adjusted'] - catalog['logmass']
    catalog = catalog.loc[
        (dm < 0.5) &
        (catalog['logmass_adjusted'] <= 11.) &
        (catalog['logmass_adjusted'] >= 7.5)
    ]

    data['catalog'] = catalog
    logger.info(f"Catalog size: {len(catalog)} objects")

    # Load H-alpha morphology
    logger.info("Loading H-alpha morphology statistics...")
    hamorph_file = '../../local_data/abby_morphology_statistics.csv'
    if os.path.exists(hamorph_file):
        hamorph = pd.read_csv(hamorph_file, index_col=0)
        hamorph['halpha_m20'] = np.where(hamorph['halpha_m20'] < -3, np.nan, hamorph['halpha_m20'])
        hamorph['continuum_m20'] = np.where(hamorph['continuum_m20'] < -3, np.nan, hamorph['continuum_m20'])
        data['hamorph'] = hamorph
        logger.info(f"Loaded morphology for {len(hamorph)} objects")
    else:
        logger.warning(f"H-alpha morphology file not found: {hamorph_file}")
        data['hamorph'] = None

    # Load satellite catalog
    logger.info("Loading satellite catalog...")
    cached_file = '../local_data/yue_meriansatellites_catalog/cached_catalog.csv'
    lucas_file = '../local_data/yue_meriansatellites_catalog/Merian_dwarf_hosts.csv'

    if os.path.exists(cached_file) and os.path.exists(lucas_file):
        yue = pd.read_csv(cached_file, index_col=0)
        lucas = pd.read_csv(lucas_file)
        lucas_trimmed = lucas[['objectId_Merian', 'coord_ra_Merian', 'coord_dec_Merian']]
        lucas_trimmed.index = [f'M{oid}' for oid in lucas_trimmed['objectId_Merian']]

        final_satellites = pd.concat([yue, lucas_trimmed])
        final_satellites = final_satellites.loc[~final_satellites.index.duplicated()]

        is_satellite = np.in1d(catalog.index, final_satellites.index)
        data['is_satellite'] = is_satellite
        logger.info(f"Identified {is_satellite.sum()} satellites")
    else:
        logger.warning("Satellite catalog not found")
        data['is_satellite'] = None

    logger.info("Data loading complete!")
    logger.info("=" * 60)

    return data

def load_data_multirun (
    source_dir: Path,
    run_names: list,
    logger: logging.Logger
):
    runs = {}
    for ix,rname in enumerate(run_names):
        runs[rname] = {
            'path': source_dir / rname,
            'label': rname,
            'color': f'C{ix+1}',
            'description': rname
        }        
    
    data = {}
    for rname in run_names:
        config_path = runs[rname]['path'] / 'effective_config.yaml'
        run_config = load_config(config_path)
        
        data[rname] = load_data(
                        run_config,
                        logger,
                        update_masses=False,
                        use_nn_classifier=True
                    )  
    
    principal_run = data[run_names[0]]
    nruns = len(data.keys())
    prob_labels_arr = np.zeros([nruns, *principal_run['prob_labels_iter'].shape])
    for ix,rname in enumerate(run_names):
        prob_labels_arr[ix] = data[rname]['prob_labels_iter']    
    
    m_prob_labels = prob_labels_arr.mean(axis=0)
    s_prob_labels = prob_labels_arr.std(axis=0)    
    
    has_label = s_prob_labels[:,1]<1.
    final_prob_labels = m_prob_labels.copy ()
    final_prob_labels[~has_label,:] = np.nan
    principal_run['prob_labels_iter'] = final_prob_labels
    principal_run['mean_prob_labels'] = m_prob_labels
    principal_run['std_prob_labels'] = s_prob_labels
    
    principal_run['possible_merger'] = (principal_run['prob_labels_iter'][:,2]+principal_run['prob_labels_iter'][:,3])>principal_run['prob_labels_iter'][:,1]
    
    return principal_run
    

def make_figure_label_distribution(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger
) -> None:
    """
    Figure 1: Label distribution histogram comparing manual vs auto-classification.

    Shows histogram of manual labels for objects classified as merger vs non-merger
    by the automatic classification system.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    """
    logger.info("Generating Figure 1: Label distribution histogram")

    fig, ax = plt.subplots(1, 1, figsize=(5, 5))

    labels = data['labels']
    is_merger = data['is_merger']
    is_undisturbed = data['is_undisturbed']

    if (labels > 0).any():
        hist_kwargs = {
            'alpha': 0.7,
            'lw': 3,
            'bins': np.arange(0.5, 5.5),
            'density': True
        }

        ek.hist(labels[is_undisturbed], 
                ax=ax, 
                label='Not merger', 
                color=colorlists.slides['grey'],                
                **hist_kwargs)
        ek.hist(
            labels[is_merger], 
            ax=ax, 
            label='Merger', 
            color=colorlists.slides['blue'],
            hatch='//',
            **hist_kwargs
        )

        ax.set_xticks(np.arange(1, 5), ['undisturbed', 'ambiguous', 'merger', 'fragmented'], rotation=35)
        ax.set_xlabel('Manual labels')
        ax.set_ylabel('Density')
        ax.legend(title='Learned classification')

    plt.tight_layout()
    if output_dir is not None:
        output_file = output_dir / 'fig1_label_distribution.pdf'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()

        logger.info(f"Saved: {output_file}")

def make_figure_classification_conflicts(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger,
    n_examples: int = 6
) -> None:
    """
    Figure 2: Example galaxies where auto and manual classifications conflict.

    Shows galaxies with low merger probability but manually labeled as non-merger,
    displaying i-band, i-band (LSB), and high-frequency images.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    n_examples : int
        Number of examples to show
    """
    logger.info("Generating Figure 2: Classification conflicts")

    img_names = data['img_names']
    labels = data['labels']
    prob_labels_iter = data['prob_labels_iter']
    n_labels_iter = data['n_labels_iter']
    pmerger = data['prob_labels_iter'][:,2] + data['prob_labels_iter'][:,3]
    fragmented = data['prob_labels_iter'][:,4] > 0.4
    data_path = data['data_path']
    label_meanings = data['label_meanings']

    manual_merger = (labels == 3) | (labels == 2)
    manual_nonmerger = labels == 1

    is_automerger = pmerger > 0.5
    mu_am = np.arange(len(img_names))[is_automerger & ~fragmented & manual_nonmerger]
    mm_au = np.arange(len(img_names))[~is_automerger & ~fragmented & manual_merger]
    
    n_examples = min(n_examples, len(mu_am))

    if n_examples == 0:
        logger.warning("No classification conflicts found")
        return

    np.random.seed(123403)
    example_indices = np.concatenate([
        np.random.choice(mu_am, n_examples//2, replace=False),
        np.random.choice(mm_au, n_examples//2, replace=False),
    ])
    print(example_indices)
    fig, axarr = plt.subplots(3, n_examples, figsize=( n_examples * 2.3, 7.))
    axarr = axarr.T

    for idx, gix in enumerate(example_indices):
        img_name = img_names[gix]
        image = load_image_by_name(img_name, data_path)

        # i-band
        ek.imshow(image[1], ax=axarr[idx, 0], q=0.01, cmap='Greys')

        # i-band log scale
        axarr[idx, 1].imshow(
            image[1],
            origin='lower',
            cmap='Greys',
            norm=colors.SymLogNorm(linthresh=0.1)
        )

        # High-frequency
        ek.imshow(image[2], ax=axarr[idx, 2], cmap='magma')

        # Add statistics
        ek.text(
            0.025, 0.025,
            f"""Pr[ud] = {prob_labels_iter[gix, 1]:.2f}
Pr[amb] = {prob_labels_iter[gix, 2]:.2f}
Pr[merg] = {prob_labels_iter[gix, 3]:.2f}
Pr[frag] = {prob_labels_iter[gix, 4]:.2f}""",
            ax=axarr[idx, 0],
            fontsize=9,
            bordercolor='w',
            color='k',
            borderwidth=3
        )
        ek.text(
            0.025,
            0.025,
            f'Human label: {label_meanings[labels[gix]]}',
            ax=axarr[idx, 1],
            fontsize=9,
            bordercolor='w',
            color= (labels[gix]==1) and 'k' or colorlists.slides['blue'],
            borderwidth=3
        )

    for ax in axarr.flatten():
        ax.set_xticks([])
        ax.set_yticks([])

    for ax in axarr[:3,:].flatten():
        ek.set_framecolor(colorlists.slides['blue'], ax=ax)
    for ax in axarr[3:,:].flatten():
        ek.set_framecolor(colorlists.slides['grey'], ax=ax)

    ek.text(0.05, 0.95, 'HSC i-band', ax=axarr[0, 0], fontsize=12,
            bordercolor='k', color='w', borderwidth=6)
    ek.text(0.05, 0.95, 'HSC i-band (LSB)', ax=axarr[0, 1], fontsize=12,
            bordercolor='k', color='w', borderwidth=6)
    ek.text(0.05, 0.95, 'Starlet HF', ax=axarr[0, 2], fontsize=12,
            bordercolor='k', color='w', borderwidth=6)

    plt.tight_layout()
    if output_dir is not None:
        output_file = output_dir / 'fig2_classification_conflicts.pdf'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()

        logger.info(f"Saved: {output_file}")


def make_figure_merger_candidates(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger,
    n_examples: int = 6
) -> None:
    """
    Figure 3: Example merger candidate galaxies.

    Shows galaxies identified as possible mergers by the automatic classification,
    displaying i-band, i-band (LSB), and high-frequency images.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    n_examples : int
        Number of examples to show
    """
    logger.info("Generating Figure 3: Merger candidates")

    img_names = data['img_names']
    prob_labels_iter = data['prob_labels_iter']
    n_labels_iter = data['n_labels_iter']
    possible_merger = (data['prob_labels_iter'][:,2]+data['prob_labels_iter'][:,3])>(data['prob_labels_iter'][:,1])
    possible_merger &= data['prob_labels_iter'][:,4] < 0.1
    possible_merger &= (data['prob_labels_iter'][:,2]>0.5)|(data['prob_labels_iter'][:,3]>0.5)
    fragmented = data['fragmented']
    data_path = data['data_path']

    candidates = np.arange(len(img_names))[possible_merger & ~fragmented]
    n_examples = min(n_examples, len(candidates))

    if n_examples == 0:
        logger.warning("No merger candidates found")
        return

    example_indices = np.random.choice(candidates, n_examples, replace=False)

    fig, axarr = plt.subplots(3, n_examples, figsize=(4 * n_examples, 10))

    for idx, gix in enumerate(example_indices):
        img_name = img_names[gix]
        image = load_image_by_name(img_name, data_path)

        # i-band
        ek.imshow(image[1], ax=axarr[0, idx], q=0.025, cmap='Greys')

        # i-band log scale
        axarr[1, idx].imshow(
            image[1],
            origin='lower',
            cmap='Greys',
            norm=colors.SymLogNorm(linthresh=0.1)
        )

        # High-frequency
        ek.imshow(image[2], ax=axarr[2, idx], cmap='magma')

        # Add statistics
        ek.text(
            0.025, 0.025,
            f"""N_labels = {n_labels_iter[gix]}
Pr[ud] = {prob_labels_iter[gix, 1]:.2f}
Pr[amb] = {prob_labels_iter[gix, 2]:.2f}
Pr[merg] = {prob_labels_iter[gix, 3]:.2f}
Pr[frag] = {prob_labels_iter[gix, 4]:.2f}""",
            ax=axarr[0, idx],
            fontsize=9,
            bordercolor='w',
            color='k',
            borderwidth=3
        )

    for ax in axarr.flatten():
        ax.set_xticks([])
        ax.set_yticks([])

    ek.text(0.05, 0.95, 'HSC i-band', ax=axarr[0, 0], fontsize=12,
            bordercolor='k', color='w', borderwidth=6)
    ek.text(0.05, 0.95, 'HSC i-band (LSB)', ax=axarr[1, 0], fontsize=12,
            bordercolor='k', color='w', borderwidth=6)
    ek.text(0.05, 0.95, 'Starlet HF', ax=axarr[2, 0], fontsize=12,
            bordercolor='k', color='w', borderwidth=6)

    plt.tight_layout()
    if output_dir is not None:
        output_file = output_dir / 'fig3_merger_candidates.pdf'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()

        logger.info(f"Saved: {output_file}")


def make_figure_ha_sfs_merger_fraction(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger
) -> None:
    """
    Figure 4: H-alpha luminosity vs stellar mass with merger probability overlay.

    Shows the star-forming sequence with color-coded average merger probability
    and scatter plot of high-confidence merger candidates.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    """
    logger.info("Generating Figure 4: H-alpha vs M* with merger fraction")

    catalog = data['catalog']

    fig, axarr = plt.subplots(1, 2, figsize=(10, 4))

    bins = [np.logspace(7.75, 10.5, 15), np.logspace(39, 41.9, 20)]
    
    cmap = ec.colormap_from_list([
        ec.ColorBase(colorlists.slides['orange']).modulate(-0.3,0.3).base, 
        ec.ColorBase(colorlists.slides['orange']).modulate(0.,-0.3).base, 
        plt.cm.coolwarm(0.5), 
        ec.ColorBase(colorlists.slides['bluebird']).modulate(0.3,-0.3).base, 
        ec.ColorBase(colorlists.slides['bluebird']).modulate(-0.1,0.5).base,    
    ])
    # Left panel: average merger probability
    im, _ = ek.pcolor_avg2d(
        10.**catalog['logmass_adjusted'],
        catalog['L_Ha'],
        catalog['p_merger'] + catalog['p_ambig'],
        cmap=cmap,
        yscale='log',
        xscale='log',
        zscale='log',
        bins=bins,
        ax=axarr[0],
    )

    # Right panel: number count histogram with scatter
    imx = ek.hist2d(
        10.**catalog['logmass_adjusted'],
        catalog['L_Ha'],
        cmap=ec.ColorBase('k').sequential_cmap(fade=1.),
        yscale='log',
        xscale='log',
        bins=bins,
        ax=axarr[1],
    )

    print(np.nanquantile((catalog['p_ambig'] + catalog['p_merger']), 0.975))
    probable_merger = (catalog['p_ambig'] + catalog['p_merger']) > np.nanquantile((catalog['p_ambig'] + catalog['p_merger']), 0.975)
    axarr[1].scatter(
        10.**catalog.loc[probable_merger, 'logmass_adjusted'],
        catalog.loc[probable_merger, 'L_Ha'],
        fc=cmap(.95),
        ec=cmap(0.8),
        s=4**2,
        #label=r'Pr[interaction] > Pr[undisturbed]'
    )
    #axarr[1].legend(loc='lower right', fontsize=10)

    # Plot star-forming sequence
    ms = im._coordinates.data[0, :, 0]
    alpha = -0.13 * 0.08 + 0.8
    norm = 1.24 * 0.08 - 1.47
    sfs = 10.**(alpha * (np.log10(ms) - 8.5) + norm)
    ha_sfs = calibrations.SFR2LHa(sfs)

    plt.colorbar(imx[0][-1], ax=axarr[1], label=r'$\langle N_{\rm merger} \rangle$')
    plt.colorbar(im, ax=axarr[0], label=r'$\langle {\rm Pr[interaction]}\rangle$')

    for ax in axarr:
        ek.outlined_plot(
            ms,
            ha_sfs,
            ax=ax,
            lw=1,
            ls='--',
        )

        ek.text(
            7e7,
            3e39,
            'EKF+24b SFS',
            ax=ax,
            rotation=37,
            coord_type='absolute',
            va='bottom',
            ha='left',
            bordercolor='w',
            borderwidth=2,
            fontsize=8,
        )
        ax.set_xlabel(ek.common_labels['mstar'])
        ax.set_ylabel(ek.common_labels['halum'])
        ek.loglog(ax=ax)

    plt.tight_layout()
    if output_dir is not None:
        output_file = output_dir / 'fig4_ha_sfs_merger_fraction.pdf'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()

        logger.info(f"Saved: {output_file}")


def make_figure_merger_fraction_vs_mass(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger
) -> None:
    """
    Figure 5: Merger detection fraction as a function of stellar mass.

    Shows the baseline merger probability and high-confidence merger fraction
    for galaxies near the star-forming sequence.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    """
    logger.info("Generating Figure 5: Merger fraction vs mass")

    catalog = data['catalog']

    # Compute SFS relation
    alpha = -0.13 * 0.08 + 0.8
    norm = 1.24 * 0.08 - 1.47
    sfs_std = 0.22 * 0.08 + 0.38
    sfs = lambda logmstar: alpha * (logmstar - 8.5) + norm

    # Compute distance from SFS
    dsfs = np.log10(calibrations.LHa2SFR(catalog['L_Ha'])) - sfs(catalog['logmass_adjusted'])
    mask = abs(dsfs / sfs_std) < 0.2

    pmerger = pd.Series(data['prob_labels_iter'][:,2] + data['prob_labels_iter'][:,3], index=data['img_names'])
    pmerger = pmerger.reindex(data['catalog'].index)

    out_baseline = sampling.running_metric(
        catalog.loc[mask, 'logmass_adjusted'],
        pmerger.loc[mask],
        np.nanmean,
        np.linspace(7., 10.25, 12),
        erronmetric=True
    )

    out_highconf = sampling.running_metric(
        catalog.loc[mask, 'logmass_adjusted'],
        (pmerger > catalog['p_undisturbed']).loc[mask],
        np.nanmean,
        np.linspace(7., 10.25, 8),
        erronmetric=True
    )

    fig, ax = plt.subplots(figsize=(6, 5))

    ek.errorbar(
        out_baseline[0].flatten(),
        out_baseline[1][:, 0, 2].flatten(),
        ylow=out_baseline[1][:, 0, 1],
        yhigh=out_baseline[1][:, 0, 3],
        label=r'Pr[interaction]-weighted',
        color=colorlists.slides['blue']
    )
    ek.errorbar(
        out_highconf[0].flatten(),
        out_highconf[1][:, 0, 2].flatten(),
        ylow=out_highconf[1][:, 0, 1],
        yhigh=out_highconf[1][:, 0, 3],
        label='High-confidence mergers',
        color=colorlists.slides['orange']
    )

    ax.legend()
    #ax.set_yscale('log')
    ax.set_xlabel(ek.common_labels['logmstar'])
    ax.set_ylabel('Merger detection fraction')

    plt.tight_layout()
    if output_dir is not None:
        output_file = output_dir / 'fig5_merger_fraction_vs_mass.pdf'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()

        logger.info(f"Saved: {output_file}")


def make_figure_merger_prob_vs_dsfs(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger
) -> None:
    """
    Figure 6: Merger probability vs distance from star-forming sequence, by mass bin.

    Shows how merger probability varies with SFR offset from the SFS,
    with separate curves for different stellar mass bins.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    """
    logger.info("Generating Figure 6: Merger probability vs dSFS by mass")

    catalog = data['catalog']

    # Compute SFS relation
    alpha = -0.13 * 0.08 + 0.8
    norm = 1.24 * 0.08 - 1.47
    sfs_std = 0.22 * 0.08 + 0.38
    sfs = lambda logmstar: alpha * (logmstar - 8.5) + norm
    
    pmerger = pd.Series(data['prob_labels_iter'][:,2] + data['prob_labels_iter'][:,3], index=data['img_names'])
    pmerger = pmerger.reindex(data['catalog'].index)
    
    u_pmerger = pd.Series((data['std_prob_labels'][:,2]**2 + data['std_prob_labels'][:,3]**2)**0.5, index=data['img_names'])
    u_pmerger = u_pmerger.reindex(data['catalog'].index)

    # Compute baseline merger probability as function of mass
    dsfs = np.log10(calibrations.LHa2SFR(catalog['L_Ha'])) - sfs(catalog['logmass_adjusted'])
    mask = abs(dsfs / sfs_std) < 0.2
    
    out_baseline = sampling.running_metric(
        catalog.loc[mask, 'logmass_adjusted'],
        pmerger.loc[mask],
        np.nanmean,
        np.linspace(8., 11., 12),
        erronmetric=True
    )
    pmerger_baseline_by_mass = lambda logmstar: np.interp(
        logmstar,
        out_baseline[0].flatten(),
        out_baseline[1][:, 0, 2].flatten()
    )

    fig, axarr = plt.subplots(1, 2, figsize=(12, 5))

    logmstar_bins = list(np.arange(8.25, 10.5, 0.3)) + [11.]
    _, logmstar_bins = sampling.bin_by_count(catalog.loc[catalog['logmass_adjusted']>8.25, 'logmass_adjusted'], 500, 0.25 )
    groups = np.digitize(catalog['logmass_adjusted'], logmstar_bins)
    groupids = np.arange(1,len(logmstar_bins))
    cmap = ec.colormap_from_list([colorlists.slides['orange'], plt.cm.coolwarm(0.5), colorlists.slides['bluebird']])

    axarr[0].set_xlim(-0.75, 3)
    axarr[0].set_ylim(0., 0.45)
    
    mask = data['catalog'].reindex(data['img_names'])['logmass_adjusted']<8.
    floor = np.mean(data['mean_prob_labels'][mask,2])
    
    for gidx, gid in enumerate(groupids):
        selected = catalog.loc[groups == gid]
        
        for idx, is_normalized in enumerate([False, True]):

            ms_at_mass = sfs(selected['logmass_adjusted'])
            dsfs = np.log10(calibrations.LHa2SFR(selected['L_Ha'])) - ms_at_mass
            assns, loglhabins = sampling.bin_by_count(dsfs, 20, 0.25)
            xs = sampling.midpts(loglhabins) / sfs_std

            if is_normalized:
                factor = 1. / (pmerger_baseline_by_mass(selected['logmass_adjusted'])-floor)
            else:
                factor = 1.
                nrml = 1.
            pm = pmerger.reindex(selected.index) - floor
            u_pm = u_pmerger.reindex(selected.index)

            _, ys, _ = sampling.running_metric(
                dsfs,
                pm * factor,
                np.nanmean,
                sampling.midpts(loglhabins),
                yerr=u_pm * factor,
                erronmetric=True
            )
            
            if is_normalized:
                nrml = np.interp(0., xs, ys[:,0,2])
            ek.outlined_plot(
                xs,
                ys[:, 0, 2]/nrml,
                lw=2,
                ax=axarr[idx],
                color=cmap(gidx / len(groupids))
            )
            axarr[idx].fill_between(
                xs,
                ys[:, 0, 1]/nrml,
                ys[:, 0, 3]/nrml,
                label=f'[{logmstar_bins[gid-1]:.2f},{logmstar_bins[gid]:.2f}]',
                alpha=0.3,
                color=cmap(gidx / len(groupids))
            )
            
            
            if not is_normalized:
                if gid < 2:
                    offset = 2
                elif gid < 3:
                    offset = 1
                elif gid == 6:
                    offset = -1
                else:
                    offset = 0
                slope = (ys[3+offset,0,2]-ys[2+offset,0,2])/(xs[3+offset]-xs[2+offset])


                ek.text(
                    sampling.midpts(xs[2+offset:4+offset]),
                    sampling.midpts(ys[2+offset:4+offset,0,2]),
                    rf'[{logmstar_bins[gid-1]:.1f},{logmstar_bins[gid]:.1f}]',
                    ha='center',
                    va='center',
                    rotation = np.rad2deg(np.arctan(slope * ek.get_subplot_aspectratio(axarr[idx]))),
                    coord_type='absolute',
                    ax=axarr[idx],
                    color=cmap(gidx / len(groupids)),
                    bordercolor='w',
                    borderwidth=3,
                    fontsize=12
                )
                
                
                if gidx == (len(groupids)-1):
                    offset = -1
                    slope = (ys[3+offset,0,2]-ys[2+offset,0,2])/(xs[3+offset]-xs[2+offset])
                    ek.text(
                        sampling.midpts(xs[2+offset:4+offset]),
                        sampling.midpts(ys[2+offset:4+offset,0,2]),  
                        r'$\log_{10}(M_\bigstar/M_\odot)$',
                        ha='center',
                        va='bottom',
                        rotation = np.rad2deg(np.arctan(slope * ek.get_subplot_aspectratio(axarr[idx]))),
                        coord_type='absolute',
                        ax=axarr[idx],
                        color=ec.ColorBase(cmap(0.5)).modulate(-0.2).base,
                        bordercolor='w',
                        borderwidth=3,
                        fontsize=13                      
                    )                

    # Add overall trend to normalized panel
    mask = (catalog['logmass_adjusted'] > logmstar_bins[0])&(catalog['logmass_adjusted'] < logmstar_bins[-1])
    xs = (np.log10(calibrations.LHa2SFR(catalog['L_Ha'])) - sfs(catalog['logmass_adjusted'])) / sfs_std
    ys = (pmerger - floor) / (pmerger_baseline_by_mass(catalog['logmass_adjusted']) - floor)
    u_ys = u_pmerger / (pmerger_baseline_by_mass(catalog['logmass_adjusted']) - floor)
    assns, loglhabins = sampling.bin_by_count(xs[(xs>-0.5)&(xs<3.5)], 20, 0.25)
    out = sampling.running_metric(xs.loc[mask], ys.loc[mask], np.nanmean,sampling.midpts(loglhabins), yerr=u_ys[mask], dx=0.4, erronmetric=True)
    nrml = np.interp(0., out[0], out[1][:,0,2])
    axarr[1].fill_between(
        out[0],
        out[1][:, 0, 1]/nrml,
        out[1][:, 0, 3]/nrml,
        color='grey',
        alpha=0.4,
    )
    ek.outlined_plot(
        out[0],
        out[1][:, 0, 2]/nrml,
        ax=axarr[1],
        ls='--',
        lw=2
    )
    
    textcolor=ec.ColorBase(cmap(0.5)).modulate(-0.2).base
    ek.arrow(
        -0.5,
        1.1,
        0.,
        10.,
        ax=axarr[1],
        color=textcolor,
    )
    ek.text(
        -0.5,
        1.3, 
        'more interactions',
        color=textcolor,
        va='bottom',
        ha='right',
        coord_type='absolute',
        rotation=90.,
        ax=axarr[1],
        fontsize=15,
    )
    
    ek.arrow(
        0.1,
        0.6,
        3.,
        0.,
        ax=axarr[1],
        color=textcolor,
    )
    ek.text(
        1.5,
        0.6, 
        'more vigorous star formation',
        color=textcolor,
        va='bottom',
        ha='center',
        coord_type='absolute',
        ax=axarr[1],
        fontsize=15
    )    
    
    lkwargs = {'ls':':', 'color':'lightgrey', 'zorder':-1}
    axarr[1].axhline(1., **lkwargs)    
    axarr[1].axvline(0., **lkwargs )
    for ax in axarr:
        ax.set_xlabel(r'$ \mathcal{S} = \frac{\log_{10}[{\rm SFR}/{\rm SFS(M_\bigstar)}]}{\sigma_{\rm SFS}}$', fontsize=20)
    axarr[0].set_ylabel(r'$\langle \rm Pr[interaction] \rangle$')
    axarr[1].set_ylabel(r'$\mathcal{R}_{\rm int}(\mathcal{S})$')
    axarr[1].set_ylim(0.5, axarr[1].get_ylim()[-1])
    axarr[1].set_yscale('log')

    plt.tight_layout()
    if output_dir is not None:
        output_file = output_dir / 'fig6_merger_prob_vs_dsfs.pdf'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()

        logger.info(f"Saved: {output_file}")


def make_figure_hamorph_distributions(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger
) -> None:
    """
    Figure 7: H-alpha morphology distributions.

    Shows distributions of asymmetry, Gini, and M20 for H-alpha emission,
    comparing unweighted, merger-probability-weighted, and high-confidence mergers.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    """
    logger.info("Generating Figure 7: H-alpha morphology distributions")

    catalog = data['catalog']
    hamorph = data['hamorph']

    if hamorph is None:
        logger.warning("H-alpha morphology data not available, skipping")
        return

    pmerger = catalog['p_merger'] + catalog['p_ambig']
    pmerger_threshold =  catalog['p_undisturbed'] #np.nanquantile((catalog['p_ambig'] + catalog['p_merger']), 0.975)

    fig, axarr = plt.subplots(1, 3, figsize=(12, 4))

    tags = {'continuum': 'continuum', 'halpha': r'H$\alpha$'}
    labels = ['Asymmetry', r'G', r'$M_{20}$']
    keys = ['asymmetry', 'gini', 'm20']

    prefix = 'halpha'

    for idx, key in enumerate(keys):
        morph_key = f'{prefix}_{key}'
        out = ek.hist(
            hamorph.reindex(catalog.index)[morph_key],
            density=True,
            alpha=0.2,
            lw=2,
            color=ec.ColorBase(colorlists.slides['grey']).base,
            hatch='//',
            label='Unweighted',
            ax=axarr[idx],
            binalpha=0.005
        )
        bins = out[1][1]
        ek.hist(
            hamorph.reindex(catalog.index)[morph_key],
            weights=pmerger,
            density=True,
            alpha=0.4,
            lw=2.,
            color=colorlists.slides['bluebird'],
            label='Weighted by Pr[interaction]',
            ax=axarr[idx],
            bins=bins
        )
        ek.hist(
            hamorph.reindex(catalog.loc[(pmerger > pmerger_threshold)].index)[morph_key],
            density=True,
            alpha=0.4,
            lw=2,
            color=colorlists.slides['orange'],
            label='High-confidence mergers',
            ax=axarr[idx],
            bins=bins
        )
        if idx == 0:
            ek.text(0.025, 0.975, 'Unweighted', color='grey', ax=axarr[idx], fontsize=11)
            ek.text(0.025, 0.9, '''Weighted by
Pr[interaction]''', color=colorlists.slides['bluebird'], ax=axarr[idx], fontsize=11)
            ek.text(0.025, 0.75, '''High-confidence
mergers''', color=colorlists.slides['orange'], ax=axarr[idx], fontsize=11)
        axarr[idx].set_xlabel(rf'{labels[idx]}({tags[prefix]})')
        if idx == 0:
            axarr[idx].set_ylabel('PDF')

    plt.tight_layout()
    plt.subplots_adjust(wspace=0.15)
    if output_dir is not None:
        output_file = output_dir / 'fig7_hamorph_distributions.pdf'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()

        logger.info(f"Saved: {output_file}")


def make_figure_hamorph_distributions_by_mass(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger,
    mass_bins: list = None
) -> None:
    """
    Figure 7b: H-alpha morphology distributions by mass bin.

    Shows distributions of asymmetry, Gini, and M20 for H-alpha emission,
    comparing unweighted, merger-probability-weighted, and high-confidence mergers,
    with each row representing a different stellar mass bin.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    mass_bins : list, optional
        Bin edges for logmstar_adjusted. Default is [7.5, 8.5, 9.5, 10.5]
    """
    logger.info("Generating Figure 7b: H-alpha morphology distributions by mass")

    catalog = data['catalog']
    hamorph = data['hamorph']

    if hamorph is None:
        logger.warning("H-alpha morphology data not available, skipping")
        return

    # Default mass bins
    if mass_bins is None:
        mass_bins = [8., 9.25, 10., 10.5]

    n_mass_bins = len(mass_bins) - 1
    pmerger = catalog['p_merger'] + catalog['p_ambig']
    pmerger_threshold = np.nanquantile((catalog['p_ambig'] + catalog['p_merger']), 0.975)

    fig, axarr = plt.subplots(n_mass_bins, 3, figsize=(12, 3.5 * n_mass_bins))

    # Ensure axarr is 2D even if only one mass bin
    if n_mass_bins == 1:
        axarr = axarr.reshape(1, -1)

    tags = {'continuum': 'continuum', 'halpha': r'H$\alpha$'}
    labels = ['Asymmetry', r'G', r'$M_{20}$']
    keys = ['asymmetry', 'gini', 'm20']
    

    prefix = 'halpha'
    from ekfphys import calibrations # XXX
    # Loop through mass bins
    for mass_idx in range(n_mass_bins):
        mass_min = mass_bins[mass_idx]
        mass_max = mass_bins[mass_idx + 1]

        # Select galaxies in this mass bin
        mass_mask = (catalog['logmass_adjusted'] >= mass_min) & (catalog['logmass_adjusted'] < mass_max)
        catalog_bin = catalog.loc[mass_mask]
        pmerger_bin = pmerger.loc[mass_mask]        
        #pmerger_bin = np.log10(calibrations.LHa2SFR(catalog_bin['L_Ha'])) - catalog_bin['logmass_adjusted']
        #pmerger_bin = (pmerger_bin - pmerger_bin.min())/(pmerger_bin.max()-pmerger_bin.min())
        #print(pmerger_bin)
        logger.info(f"  Mass bin [{mass_min}, {mass_max}): {len(catalog_bin)} galaxies")

        # Loop through morphology parameters
        for idx, key in enumerate(keys):
            morph_key = f'{prefix}_{key}'

            # Unweighted histogram
            out = ek.hist(
                hamorph.reindex(catalog_bin.index)[morph_key],
                density=True,
                alpha=0.2,
                lw=2,
                color=ec.ColorBase(colorlists.slides['grey']).base,
                hatch='//',
                label='Unweighted',
                ax=axarr[mass_idx, idx],
                binalpha=0.01,
                bins=15,
            )
            bins = out[1][1]

            # Weighted by merger probability
            ek.hist(
                hamorph.reindex(catalog_bin.index)[morph_key],
                weights=pmerger_bin,
                density=True,
                alpha=0.4,
                lw=2.,
                color=colorlists.slides['bluebird'],
                label='Weighted by Pr[interaction]',
                ax=axarr[mass_idx, idx],
                bins=bins
            )

            # High-confidence mergers only
            high_conf_mask = pmerger_bin > pmerger_threshold
            if high_conf_mask.sum() > 10:
                ek.hist(
                    hamorph.reindex(catalog_bin.loc[high_conf_mask].index)[morph_key],
                    density=True,
                    alpha=0.4,
                    lw=2,
                    color=colorlists.slides['orange'],
                    label='High-confidence mergers',
                    ax=axarr[mass_idx, idx],
                    bins=bins
                )

            # Add legend/labels to first column only
            if (idx == 0):
                if mass_idx == 0:
                    ek.text(0.025, 0.975, 'Unweighted', color='grey', ax=axarr[mass_idx, idx], fontsize=11)
                    ek.text(0.025, 0.9, '''Weighted by
    Pr[interaction]''', color=colorlists.slides['blue'], ax=axarr[mass_idx, idx], fontsize=11)                    
                if (mass_idx == (n_mass_bins-1)):
                    ek.text(0.025, 0.975, '''High-confidence
    mergers''', color=colorlists.slides['orange'], ax=axarr[mass_idx, idx], fontsize=11)

                # Add mass bin label
                ek.text(0.975, 0.975, f'${mass_min:.1f} < \\log M_* < {mass_max:.1f}$',
                       ax=axarr[mass_idx, idx], fontsize=12, ha='right')

            # Set x-label (only on bottom row)
            #if mass_idx == n_mass_bins - 1:
            axarr[mass_idx, idx].set_xlabel(rf'{labels[idx]}({tags[prefix]})')

            # Set y-label (only on first column)
            if idx == 0:
                axarr[mass_idx, idx].set_ylabel('PDF')

    plt.tight_layout()
    #plt.subplots_adjust(wspace=0.15, hspace=0.2)
    if output_dir is not None:
        output_file = output_dir / 'fig7b_hamorph_distributions_by_mass.pdf'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()

        logger.info(f"Saved: {output_file}")


def make_hamorph_differential(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger
) -> None:
    """
    Figure: H-alpha morphology differential analysis by mass bin.

    Shows the ratio of unweighted to merger-weighted distributions for
    continuum and H-alpha morphology parameters (asymmetry, Gini, M20)
    across different stellar mass bins.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    """
    logger.info("Generating Figure: H-alpha morphology differential")

    catalog = data['catalog']
    hamorph = data['hamorph']

    if hamorph is None:
        logger.warning("H-alpha morphology data not available, skipping")
        return

    # Get merger probability CDF
    cdf = pd.DataFrame({'pmerger': data['prob_labels_iter'][:,2] + data['prob_labels_iter'][:,3]},
                       index=data['img_names'])

    # Setup mass bins (matching make_figure_merger_prob_vs_dsfs)
    _, logmstar_bins = sampling.bin_by_count(
        catalog.loc[catalog['logmass_adjusted'] > 8.25, 'logmass_adjusted'],
        1000,
        0.5
    )
    logmstar_bins = np.linspace(8., 10., 5)

    xbins = np.linspace(8., 10.5, 5)
    
    dx = 0.75
    bin_indices = np.arange(len(xbins))

    # Setup colormap (matching make_figure_merger_prob_vs_dsfs)
    cmap = ec.colormap_from_list([
        colorlists.slides['orange'],
        plt.cm.coolwarm(0.5),
        colorlists.slides['bluebird']
    ])

    # Create figure with 2 rows (continuum, halpha) and 3 columns (asymmetry, gini, m20)
    fig, axarr = plt.subplots(2, 2, figsize=(10,8))

    prefixes = ['continuum', 'halpha']
    keys = ['asymmetry', 'gini']#, 'm20']
    xlabels = {'asymmetry': 'Asymmetry', 'gini': 'Gini', 'm20': r'M$_{20}$'}

    # Loop over prefixes (rows) and keys (columns)
    #for ax in axarr.flatten():
    #    ax.set_ylim(0.3,2.,)
    
    
    for row_idx, prefix in enumerate(prefixes):
        for col_idx, key in enumerate(keys):
            ax = axarr[row_idx, col_idx]
            morph_key = f'{prefix}_{key}'
            logger.info(f"Processing {morph_key}")
                        
            # Define y-bins using quantile clipping
            eps = 0.05
            vals = np.quantile(
                sampling.sigmaclip(
                    sampling.fmasker(data['hamorph'].reindex(data['catalog'].index)[morph_key].values)
                ).clipped,
                [eps, 1 - eps]
            )
            ybins = np.linspace(*vals, 100)
            histybins = np.linspace(*vals, 20)            

            if False:
                (_,_,spacing), _=ek.histstack(
                    data['catalog']['logmass_adjusted'].values,
                    data['hamorph'].reindex(data['catalog'].index)[morph_key].values,
                    ybins=histybins,
                    xbins=logmstar_bins,
                    show_quantile=False,
                    color=colorlists.slides['grey'],
                    linewidth=1,
                    ax=ax,
                )

                ek.histstack(
                    data['catalog']['logmass_adjusted'].values,
                    data['hamorph'].reindex(data['catalog'].index)[morph_key].values,
                    w=cdf.reindex(data['catalog'].index)['pmerger'].values,
                    ybins=histybins,
                    xbins=logmstar_bins,
                    spacing=spacing,
                    show_quantile=False,
                    color=colorlists.slides['bluebird'],
                    linewidth=1,
                    ax=ax,
                )



            # Assign mass bins
            assns = np.digitize(data['catalog']['logmass_adjusted'], xbins)

            # Loop over mass bins
            npull=10
            modes = np.zeros([len(bin_indices), npull, 2])
            for gidx, bin_idx in enumerate(bin_indices):
                mass_mask = (
                    abs(data['catalog']['logmass_adjusted'] - xbins[bin_idx]) < dx
                )
                # Get morphology values for this mass bin
                morph_vals = data['hamorph'].reindex(data['catalog'].index)[morph_key].values[mass_mask]
                pmerger_vals = cdf.reindex(data['catalog'].index)['pmerger'].values[mass_mask]
                morph_vals = np.where(
                    (morph_vals<ybins[0])|(morph_vals>ybins[-1]),
                    np.nan,
                    morph_vals
                )
                morph_vals, pmerger_vals = sampling.fmasker(morph_vals,pmerger_vals)
            
                # Bootstrap histogram counts
                
                ratio = np.zeros([npull, len(ybins)])
                #modes = np.zeros([npull, 2])
                for _ in range(npull):
                    choice = np.random.choice(range(len(morph_vals)), size=len(morph_vals), replace=True)
                    choice2 = np.random.choice(range(len(morph_vals)), size=len(morph_vals), replace=True)
                    c_morph_vals = morph_vals[choice]      
                    b_morph_vals = morph_vals[choice2]              
                    c_pmerger_vals = pmerger_vals[choice]
                    b_pmerger_vals = pmerger_vals[choice2]
                    dwass = stats.wasserstein_distance(c_morph_vals, b_morph_vals, v_weights=b_pmerger_vals)
                    #dwass = stats.wasserstein_distance(c_morph_vals, b_morph_vals)
                    dwass_ref = stats.wasserstein_distance(c_morph_vals, b_morph_vals)
                    modes[gidx,_,1] = dwass
                    modes[gidx,_,0] = dwass_ref
                    if False:
                        modes[gidx,_,0] = np.mean(c_morph_vals)
                        modes[gidx,_,1] = np.sum(c_morph_vals*c_pmerger_vals)/np.sum(c_pmerger_vals)
                        continue
                        uw_gkde = gaussian_kde(c_morph_vals, )
                        w_gkde = gaussian_kde(c_morph_vals, weights=c_pmerger_vals)
                        ratio[_] = w_gkde(ybins)/uw_gkde(ybins)
                        modes[gidx,_,0] = ybins[np.argmax(uw_gkde(ybins))]
                        modes[gidx,_,1] = ybins[np.argmax(w_gkde(ybins))]
                
                # Get color for this mass bin
                color = cmap(gidx / len(bin_indices))
               
                #ax.plot(
                #    ybins,
                #    ratio_median,
                #    color=color,
                #    lw=2
                #)
                #ax.fill_between(
                #    ybins,
                #    ratio_16,
                #    ratio_84,
                #    alpha=0.3,
                #    color=color
                #)

                # Add in-line legend (only for middle column to avoid clutter)
                #if col_idx == 0:
                #    # Find a good y-position for the label
                #    #mid_idx = len(ratio_median) // 2
                #    #label_y = ratio_median[mid_idx]

                #    ek.text(
                #        0.975,
                #        0.025 + (bin_idx-1)*.075,
                #        #sampling.midpts(ybins)[mid_idx],
                #        #label_y,
                #        f'[{xbins[bin_idx-1]:.2f},{xbins[bin_idx]:.2f}]',
                #        color=color,
                #        fontsize=12,
                #        #bbox=dict(boxstyle='round,pad=0.3', #facecolor='white', edgecolor='none', alpha=0.7),
                #        ax=ax
                #    )

            # Plot
            eps = 0.025
            for idx, cc in enumerate(['grey', colorlists.slides['bluebird']]):
                if False:
                    ek.outlined_plot(
                        xbins,
                        np.median(modes[:,:,idx], axis=1),
                        ax=ax,
                        color=cc,
                    )
                    ax.fill_between(
                        xbins,
                        np.quantile(modes[:,:,idx], eps,axis=1),
                        np.quantile(modes[:,:,idx], 1.-eps,axis=1),                
                        color=cc,
                        alpha=0.3
                    )   
                else:
                    ek.errorbar(
                        xbins,
                        np.median(modes[:,:,idx], axis=1),
                        ylow=np.quantile(modes[:,:,idx], eps,axis=1),
                        yhigh=np.quantile(modes[:,:,idx], 1.-eps,axis=1),
                        color=cc,  
                        ax=ax                      
                    )         

            # Add grey legend title above the most massive bin (only for middle column)
            #if col_idx==0:                
            #    ek.text(
            #        0.975,
            #        0.025 + (bin_idx+1)*0.075,
            #        r'$\log_{10}(M_\bigstar/M_\odot)$',
            #        ax=ax,
            #        ha='right',
            #        va='top',
            #        color=ec.ColorBase(cmap(0.5)).modulate(-0.2).base,
            #        fontsize=11,
            #        coord_type='relative'
            #    )

            # Add horizontal line at y=1
            #ax.axhline(1., color='grey', ls=':', zorder=-1)

            # Add prefix label (continuum or halpha)
            prefix_label = 'continuum' if prefix == 'continuum' else r'H$\alpha$'
            ek.text(0.025, 0.975, prefix_label, ax=ax, fontsize=14, ha='left', va='top')

            # Add x-label
            ax.set_xlabel(xlabels[key])

            # Add y-label (only for first column)
            #if col_idx == 0:
            ax.set_ylabel('Wasserstein distance')

    plt.tight_layout()
    if output_dir is not None:
        output_file = output_dir / 'fig_hamorph_differential.pdf'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()

        logger.info(f"Saved: {output_file}")
    return axarr


def make_figure_gini_m20_space(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger
) -> None:
    """
    Figure 8: Gini-M20 diagram with merger probability.

    Shows the distribution of galaxies in Gini-M20 space with color-coded
    merger probability, including Lotz et al. classification boundaries.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    """
    logger.info("Generating Figure 8: Gini-M20 diagram")

    catalog = data['catalog']
    hamorph = data['hamorph']

    if hamorph is None:
        logger.warning("H-alpha morphology data not available, skipping")
        return

    pmerger = catalog['p_merger'] + catalog['p_ambig']

    fig, ax = plt.subplots(figsize=(7, 6))

    
    ek.pcolor_avg2d(
        hamorph.reindex(catalog.index)['continuum_m20'],
        hamorph.reindex(catalog.index)['continuum_gini'],
        pmerger,
        bins=[np.linspace(-2.5, -0.5, 30), np.linspace(0.3, 0.8, 30)],
        cmap=cmap,
        vmin=0.,
        vmax=0.16
    )
    ek.density_contour(
        hamorph.reindex(catalog.index)['continuum_m20'],
        hamorph.reindex(catalog.index)['continuum_gini'],
        quantiles=[0.16, 0.5, 0.9, 0.95, 0.975],
        colors='w'
    )

    # Lotz et al. classification boundaries
    lotza = np.array([[-3.0065789473684212, 0.3799999999999999],
                      [-1.6776315789473686, 0.56375]])
    lotzb = np.array([[-3.0000000000000004, 0.75],
                      [-0.0065789473684203514, 0.33124999999999993]])

    ek.outlined_plot(lotza[:, 0], lotza[:, 1], ls=':', lw=1, color='grey')
    ek.outlined_plot(lotzb[:, 0], lotzb[:, 1], ls=':', lw=1, color='grey')

    ax.set_xlabel("M20")
    ax.set_ylabel("Gini")
    ax.set_xlim(-2.5, -0.5)
    ax.set_ylim(0.3, 0.75)

    plt.colorbar(ax.collections[0], ax=ax, label=r'$\langle \rm Pr[interaction] \rangle$')
    plt.tight_layout()
    output_file = output_dir / 'fig8_gini_m20_space.pdf'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    plt.close()

    logger.info(f"Saved: {output_file}")


def make_hamorph_differential_split(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger
) -> pd.DataFrame:
    """
    Figure: H-alpha and Continuum morphology differential analysis by mass bin (split into two figures).

    Creates two separate figures (one for continuum, one for H-alpha), each showing:
    - Top row: Cumulative distribution functions for asymmetry and Gini
    - Bottom row: Differential (unweighted CDF - weighted CDF) for asymmetry and Gini

    Each morphology parameter is color-coded by stellar mass bin.

    Also performs Kolmogorov-Smirnov tests on weighted vs. unweighted morphology distributions.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance

    Returns
    -------
    pvals_df : pd.DataFrame
        DataFrame with KS test p-values indexed by (tracer, morphstat, mass_bin) with columns
        ['p_lesser', 'p_greater', 'p_twosided'] corresponding to one-sided and two-sided KS tests.
        lesser: weighted sample skews higher
        greater: weighted sample skews lower
    """
    logger.info("Generating Figure: H-alpha and Continuum morphology differential (split)")

    catalog = data['catalog']
    hamorph = data['hamorph']

    if hamorph is None:
        logger.warning("H-alpha morphology data not available, skipping")
        return

    # Get merger probability CDF
    cdf = pd.DataFrame({'pmerger': data['prob_labels_iter'][:,2] + data['prob_labels_iter'][:,3]},
                       index=data['img_names'])

    # Setup mass bins and colormap
    xbins = np.linspace(8.25, 10., 10)
    dx = 1.0

    # Y-bins for different tracers and morphology stats
    ybins_dict = {
        'continuum': {
            'asymmetry': np.linspace(-0.4, 0.5, 30),
            'gini': np.linspace(0.3, 0.7, 30)
        },
        'halpha': {
            'asymmetry': np.linspace(-0.5, 0.75, 30),
            'gini': np.linspace(0.35, 0.8, 30)
        }
    }

    # Y-limits for differential plots
    ylims = {'asymmetry': (-0.05, 0.15), 'gini': (-0.04, 0.1)}

    # Morphology parameters
    morphstats = ['asymmetry', 'gini']
    morphlabels = [r'$\mathcal{A}$', r'$\mathcal{G}$']
    morph_names = ['asymmetry', 'Gini']

    # Tracers
    tracers = ['continuum', 'halpha']
    tracer_sub = ['c', r'\rm H\alpha']
    tracer_names = ['continuum', r'H$\alpha$']

    # Initialize dictionary to store KS test p-values
    # Structure: pvals_dict[(tracer, morphstat, mass_bin)] = (p_lesser, p_greater, p_twosided)
    pvals_dict = {}

    # Loop through tracers to create two separate figures
    for tdx, tracer in enumerate(tracers):
        logger.info(f"  Generating {tracer} figure...")

        # Create figure with 2x2 grid
        fig, axarr = plt.subplots(2, 2, figsize=(10, 6))

        # Loop through morphology statistics
        for mdx, ms in enumerate(morphstats):
            key = f'{tracer}_{ms}'

            # Get axes for this morphology stat
            ax = axarr[0, mdx]  # Top row: CDF
            bx = axarr[1, mdx]  # Bottom row: Differential

            # Get y-bins for this tracer and morphology stat
            ybins = ybins_dict[tracer][ms]

            # Set x-limits
            ax.set_xlim(ybins[0], ybins[-1])
            bx.set_xlim(ybins[0], ybins[-1])

            # Loop over mass bins
            for mass_idx, mass_mid in enumerate(xbins):
                mass_mask = abs(data['catalog']['logmass_adjusted'].values - mass_mid) < dx

                # Get color for this mass bin
                cc = cmap((mass_mid - xbins.min()) / (xbins.max() - xbins.min()))

                # Get morphology and weight values for this mass bin
                morph_values = data['hamorph'].reindex(data['catalog'].index)[key].values[mass_mask]
                weight_values = cdf.reindex(data['catalog'].index)['pmerger'].values[mass_mask]

                # Unweighted cumulative histogram
                out = ek.hist(
                    morph_values,
                    cumulative=True,
                    density=True,
                    histtype='step',
                    ax=ax,
                    color=cc,
                    bins=ybins,
                    lw=2
                )
                unweighted_counts = out[1][0]

                # Weighted histogram
                out = np.histogram(
                    morph_values,
                    weights=weight_values,
                    bins=ybins,
                    density=True,
                )

                # Convert to cumulative
                weighted_counts = np.cumsum(out[0]) / np.sum(out[0])

                # Plot differential
                bx.step(
                    sampling.midpts(ybins),
                    unweighted_counts - weighted_counts,
                    where='mid',
                    color=cc,
                    lw=2
                )

                # Perform KS tests on weighted vs unweighted samples
                # Create weighted morphology sample using random choice with probability weights
                morph_samp = morph_values.copy()
                ps = np.where(np.isfinite(morph_samp), weight_values, 0.)

                # Generate weighted sample by random choice
                if np.sum(ps) > 0:
                    wmorph_samp = np.random.choice(
                        morph_samp,
                        p=ps / np.sum(ps),
                        replace=True,
                        size=morph_samp.size
                    )

                    # KS tests: lesser = weighted skews higher, greater = weighted skews lower
                    weighted_towards_lesser = stats.ks_2samp(
                        *sampling.fmasker(morph_samp, wmorph_samp),
                        alternative='lesser'
                    )
                    weighted_towards_greater = stats.ks_2samp(
                        *sampling.fmasker(morph_samp, wmorph_samp),
                        alternative='greater'
                    )
                    weighted_is_same = stats.ks_2samp(
                        *sampling.fmasker(morph_samp, wmorph_samp),
                        alternative='two-sided'
                    )

                    # Store p-values
                    pvals_dict[(tracer, ms, mass_mid)] = (
                        weighted_towards_lesser.pvalue,
                        weighted_towards_greater.pvalue,
                        weighted_is_same.pvalue
                    )
                else:
                    # No valid weights, store NaN
                    pvals_dict[(tracer, ms, mass_mid)] = (np.nan, np.nan, np.nan)

            # Add horizontal line at 0 for differential plot
            bx.axhline(0., ls=':', color='lightgrey')

            # Add colorbar to first subplot only
            if mdx == 0:
                ek.colorbar_inset(
                    cmap,
                    xbins[0],
                    xbins[-1],
                    x=0.7,
                    y=0.1,
                    height=0.6,
                    width=0.05,
                    label=ek.common_labels['logmstar'],
                    orientation='vertical',
                    ax=ax
                )

            # Labels
            mlbl = rf'{morphlabels[mdx]}$_{{{tracer_sub[tdx]}}}$'
            bx.set_xlabel(rf'{mlbl}$=${morph_names[mdx].capitalize()}, {tracer_names[tdx]}')
            ax.set_ylabel(rf'F({mlbl})')
            bx.set_ylabel(rf'F({mlbl}) - F$_w$({mlbl})', labelpad=-10)
            ax.set_xticks([])
            bx.set_ylim(ylims[ms])
            bx.set_yticks(bx.get_yticks()[:-1])

        # Adjust layout
        plt.tight_layout()
        plt.subplots_adjust(wspace=0.35, hspace=0.02)

        # Add colored background to differential plots
        for ax in axarr[1]:
            ax.autoscale(enable=False, axis='y')

            # Red background for positive values (shifted higher)
            ax.axhspan(
                0.,
                ax.get_ylim()[1],
                color=ec.ColorBase(colorlists.slides['red']).modulate(0.5).base,
                zorder=-1
            )
            # Yellow background for negative values (shifted lower)
            ax.axhspan(
                ax.get_ylim()[0],
                0.,
                color=ec.ColorBase(colorlists.slides['yellow']).modulate(0.3).base,
                zorder=-1
            )

        # Add annotation text to first differential subplot
        ax_text = axarr[1, 0]
        ek.text(
            0.975,
            0.025,
            '''Pr[TF]-weighted
PDF shifted lower''',
            color=ec.ColorBase(colorlists.slides['yellow']).modulate(-0.3).base,
            ax=ax_text,
            fontsize=12
        )
        ek.text(
            0.975,
            0.975,
            '''Pr[TF]-weighted
PDF shifted
higher''',
            color=colorlists.slides['red'],
            ax=ax_text,
            fontsize=12
        )

        # Save figure
        if output_dir is not None:
            output_file = output_dir / f'fig_hamorph_differential_{tracer}.pdf'
            plt.savefig(output_file, dpi=300, bbox_inches='tight')
            plt.close()
            logger.info(f"Saved: {output_file}")
        else:
            plt.show()

    # Convert p-values dictionary to DataFrame
    # Create multi-index from dictionary keys
    index_tuples = list(pvals_dict.keys())
    index = pd.MultiIndex.from_tuples(index_tuples, names=['tracer', 'morphstat', 'mass_bin'])

    # Create DataFrame with p-value columns
    pvals_df = pd.DataFrame(
        list(pvals_dict.values()),
        index=index,
        columns=['p_lesser', 'p_greater', 'p_twosided'],
    ).round(2)
    pvals_df['description'] =  ''
    for name,row in pvals_df.iterrows():
        s = ''
        if row.p_twosided > 0.05:
            s = 'Statistically indistinct from reference;'
        else:
            #if (row.p_lesser > 0.05) and (row.p_greater>0.05):
            #    s = 'Statistically indistinguishable between shifted down and up'
            if row.p_lesser > 0.05:
                s = s + 'Consistent with f_w shifted higher;'
            if row.p_greater > 0.05:
                s = s + 'Consistent with f_w shifted lower;'
        if s == '':
            s = 'Statistically distinct from ref w/o monotonic shift'
        s = s.strip(';')
        pvals_df.loc[name, 'description'] = s
    logger.info(f"Computed KS test p-values for {len(pvals_df)} combinations")

    return pvals_df


def mk_appendix_metric(
    output_dir: Path,
    logger: logging.Logger,
    n_samples: int = 3000,
    base_mean: float = 3.0,
    base_std: float = 1.0
) -> None:
    """
    Appendix Figure: Demonstration of differential CDF metric using synthetic data.

    Creates a diagnostic figure showing how the differential CDF metric responds to
    controlled shifts in distribution mean and standard deviation. Four test cases
    are shown with known parameter shifts.

    Parameters
    ----------
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    n_samples : int, optional
        Number of samples to generate for each distribution (default: 3000)
    base_mean : float, optional
        Mean of the base distribution (default: 3.0)
    base_std : float, optional
        Standard deviation of the base distribution (default: 1.0)
    """
    logger.info("Generating Appendix Figure: Differential CDF metric demonstration")

    # Generate base distributions (same for all 4 test cases)
    xs = [
        np.random.normal(base_mean, base_std, n_samples),
        np.random.normal(base_mean, base_std, n_samples),
        np.random.normal(base_mean, base_std, n_samples),
        np.random.normal(base_mean, base_std, n_samples)
    ]

    # Define parameter shifts: (delta_mean, delta_std)
    params = [(0.1, 0.), (-0.1, 0.), (0., 0.1), (0., -0.1)]

    # Generate shifted distributions
    ys = [
        np.random.normal(base_mean + p[0], base_std + p[1], n_samples)
        for p in params
    ]

    # Create figure
    fig, axarr = plt.subplots(2, 4, figsize=(12, 5.5))

    # Loop through each test case
    for colidx in range(len(ys)):
        x = xs[colidx]
        y = ys[colidx]

        # Compute bins from combined data quantiles
        eps = 1e-3
        bins = np.linspace(*np.quantile(np.concatenate([x, y]), [eps, 1. - eps]), 30)

        # Top panel: PDFs
        ax = axarr[0, colidx]
        ek.hist(x, density=True, alpha=0.3, lw=2, ax=ax, bins=bins, color='grey')
        ek.hist(y, density=True, alpha=0.3, lw=2, ax=ax, bins=bins)

        # Compute CDFs
        out = np.histogram(x, density=True, bins=bins)
        unweighted_counts = np.cumsum(out[0]) / np.sum(out[0])
        out = np.histogram(y, density=True, bins=bins)
        weighted_counts = np.cumsum(out[0]) / np.sum(out[0])

        # Bottom panel: Differential CDF
        ax = axarr[1, colidx]
        ax.autoscale(enable=False, axis='y')
        ax.step(
            sampling.midpts(bins),
            unweighted_counts - weighted_counts,
            where='mid',
            lw=2,
        )
        ax.set_ylim(-0.06, 0.06)
        
        ax.axhline(0., ls=':', color='grey')

        # Add parameter annotations
        dm, ds = params[colidx]
        ek.text(
            0.025,
            0.975,
            rf'''$\Delta \mu = {{{dm:.1f}}}$
$\Delta \sigma = {{{ds:.1f}}}$''',
            ax=axarr[0, colidx]
        )

        # Clean up tick labels
        axarr[0, colidx].set_xticklabels([])
        if colidx == 0:  # Only modify y-tick labels for leftmost column
            yticks = axarr[1, colidx].get_yticks()
            axarr[1, colidx].set_yticks(yticks[:-1])  # Remove only the last (topmost) tick
            axarr[1,colidx].set_ylim(-0.06,0.06)

    # Hide y-tick labels for all but leftmost column
    for ax in axarr[:, 1:].flatten():
        ax.set_yticklabels([])

    # Adjust layout
    plt.tight_layout()
    plt.subplots_adjust(hspace=0.0, wspace=0.)

    # Add colored backgrounds to differential plots
    for ax in axarr[1]:
        

        # Red background for positive values (shifted higher)
        ax.axhspan(
            0.,
            ax.get_ylim()[1],
            color=ec.ColorBase(colorlists.slides['red']).modulate(0.5).base,
            zorder=-1
        )
        # Yellow background for negative values (shifted lower)
        ax.axhspan(
            ax.get_ylim()[0],
            0.,
            color=ec.ColorBase(colorlists.slides['yellow']).modulate(0.3).base,
            zorder=-1
        )
        ax.set_xlabel('x')

    # Set y-axis label for top-left panel
    axarr[0, 0].set_ylabel(r'$F(x)$')
    axarr[1, 0].set_ylabel(r'$F_a(x) - F_b(x)$')

    # Save figure
    if output_dir is not None:
        output_file = output_dir / 'fig_appendix_differential_metric.pdf'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()
        logger.info(f"Saved: {output_file}")
    else:
        plt.show()


def make_figure_merger_prob_vs_environment(
    data: Dict,
    output_dir: Path,
    logger: logging.Logger
) -> None:
    """
    Figure 9: Merger probability vs environment.

    Shows merger probability as a function of SFR offset from SFS,
    comparing satellites and centrals/field galaxies.

    Parameters
    ----------
    data : dict
        Data dictionary from load_data()
    output_dir : Path
        Output directory for figures
    logger : logging.Logger
        Logger instance
    """
    logger.info("Generating Figure 9: Merger probability vs environment")

    catalog = data['catalog']
    is_satellite = data['is_satellite']

    if is_satellite is None:
        logger.warning("Satellite data not available, skipping")
        return

    # Compute SFS relation
    alpha = -0.13 * 0.08 + 0.8
    norm = 1.24 * 0.08 - 1.47
    sfs_std = 0.22 * 0.08 + 0.38
    sfs = lambda logmstar: alpha * (logmstar - 8.5) + norm

    pmerger = catalog['p_merger'] + catalog['p_ambig']

    # Compute baseline merger probability
    dsfs = np.log10(calibrations.LHa2SFR(catalog['L_Ha'])) - sfs(catalog['logmass_adjusted'])
    mask = abs(dsfs / sfs_std) < 0.2

    out_baseline = sampling.running_metric(
        catalog.loc[mask, 'logmass_adjusted'],
        pmerger.loc[mask],
        np.nanmean,
        np.linspace(7., 10.25, 12),
        erronmetric=True
    )
    pmerger_baseline_by_mass = lambda logmstar: np.interp(
        logmstar,
        out_baseline[0].flatten(),
        out_baseline[1][:, 0, 2].flatten()
    )

    fig, axarr = plt.subplots(1,2, figsize=(10,5))

    xs = (np.log10(calibrations.LHa2SFR(catalog['L_Ha'])) - sfs(catalog['logmass_adjusted'])) / sfs_std
    ys = pmerger / pmerger_baseline_by_mass(catalog['logmass_adjusted'])

    ax = axarr[1]
    for envkey in [0, 1]:
        if envkey == 0:
            envmask = ~is_satellite
            env_indices = sampling.make_matched_sample(     
                catalog.loc[~is_satellite, 'logmass_adjusted'],
                catalog.loc[is_satellite, 'logmass_adjusted'],  
                #n_sample=5*is_satellite.sum()
            ).index
            #env_indices = catalog.loc[envmask].index
        elif envkey == 1:
            envmask = is_satellite
            env_indices = catalog.loc[envmask].index

        out = sampling.running_metric(
            xs.reindex(env_indices),
            ys.reindex(env_indices),
            np.nanmean,
            np.arange(-0.5, 3.75, 0.4),
            dx=0.5,
            erronmetric=True
        )
        cc = [colorlists.slides['blue'], colorlists.slides['red']][envkey]
        ax.fill_between(
            out[0],
            out[1][:, 0, 1],
            out[1][:, 0, 3],
            color=cc,
            alpha=0.4,
            hatch=envkey == 1 and '||' or None,
        )
        ek.outlined_plot(
            out[0],
            out[1][:, 0, 2],
            ax=ax,
            color=cc,
            lw=2,
            label=['Field? (sat mass-matched)', 'Satellite'][envkey]
        )
        #ek.hist(
        #    catalog.reindex(env_indices)['logmass_adjusted'],
        #    color=cc,
        #    alpha=0.3,
        #    ax=axarr[2],
        #    density=True
        #)

    ax.set_xlabel(r'$\mathcal{S}\equiv \frac{\log_{10}[{\rm SFR}/{\rm SFS(M_\bigstar)}]}{\sigma_{\rm SFS}}$', fontsize=20)
    #ax.set_ylabel(r'$\mathcal{q} \equiv \langle {\rm Pr[interaction]}\rangle/\langle \rm Pr[interaction|SFS] \rangle$')
    ax.set_ylabel(r'Excess mean interaction probability')
    ax.axhline(1., color='lightgrey', ls=':')
    
    ax.legend()

    # Top panel: SFR offset distributions
    xbins = np.linspace(min(out[0]), max(out[0]), 30)
    cc = [colorlists.slides['blue'], colorlists.slides['red']]
    lbls = ['Field?', 'Satellite']
    for envidx, mask in enumerate([~is_satellite, is_satellite]):
        hcounts = sampling.bootstrap_histcounts(
            xs[mask],
            bins=xbins
        )
        cumulative_hist = np.cumsum(hcounts, axis=1)/np.sum(hcounts,axis=1).reshape(-1,1)
        if envidx == 0:
            nrml = np.quantile(cumulative_hist, 0.5, axis=0)
        
        axarr[0].fill_between(
            sampling.midpts(xbins),
            np.quantile(cumulative_hist, 0.16, axis=0)/nrml,
            np.quantile(cumulative_hist, 0.84, axis=0)/nrml,
            alpha=0.3,
            color = cc[envidx],
            step='mid'
        )
        axarr[0].step(
            sampling.midpts(xbins),
            np.quantile(cumulative_hist, 0.5, axis=0)/nrml,
            lw=2, 
            color=cc[envidx],
            where='mid',
            label=lbls[envidx]
        )
    axarr[0].set_ylabel(r'$N(<\mathcal{S})/N_{\rm tot}$')
    axarr[0].set_xlabel(r'$\mathcal{S}\equiv \frac{\log_{10}[{\rm SFR}/{\rm SFS(M_\bigstar)}]}{\sigma_{\rm SFS}}$', fontsize=20)
    axarr[0].legend()

    for ax in axarr:
        ax.grid(axis='x', color='lightgrey')
    plt.tight_layout()
    if output_dir is not None:
        output_file = output_dir / 'fig9_merger_prob_vs_environment.pdf'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()

        logger.info(f"Saved: {output_file}")


def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(
        description='Generate punchline figures from merger analysis',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate all figures using default config
  python make_punchlines.py

  # Use custom config
  python make_punchlines.py --config ../custom_config.yaml

  # Specify output directory
  python make_punchlines.py --output-dir ../figures/

  # Generate only specific figures (comma-separated)
  python make_punchlines.py --figures 1,2,3
        """
    )

    parser.add_argument(
        '--config',
        type=str,
        default='../config.yaml',
        help='Path to configuration YAML file'
    )

    parser.add_argument(
        '--output-dir',
        type=str,
        default='./punchline_figures/',
        help='Output directory for figures'
    )

    parser.add_argument(
        '--input-path',
        type=str,
        default=None,
        help='Path to input data directory (overrides config["data"]["output_path"])'
    )

    parser.add_argument(
        '--figures',
        type=str,
        help='Comma-separated list of figure numbers to generate (1-9). If not specified, generates all.'
    )

    parser.add_argument(
        '--seed',
        type=int,
        default=42,
        help='Random seed for reproducibility'
    )

    args = parser.parse_args()

    # Setup logging
    logger = setup_logging('INFO')

    try:
        # Set random seed
        np.random.seed(args.seed)

        # Load configuration
        config = load_config(args.config, input_path=args.input_path)
        logger.info(f"Configuration loaded from: {args.config}")
        if args.input_path:
            logger.info(f"Input path overridden to: {args.input_path}")

        # Create output directory
        output_dir = Path(args.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"Output directory: {output_dir}")

        # Load data
        #data = load_data(config, logger)
        data = load_data_multirun(Path('../output/'), 
                                  ['fiducial'] + [ f'fiducial_rerun_{ix}' for ix in range(5)],
                                  logger)

        # Determine which figures to generate
        if args.figures:
            figure_nums = [int(x.strip()) for x in args.figures.split(',')]
        else:
            figure_nums = list(range(1, 10))

        logger.info("=" * 60)
        logger.info(f"GENERATING FIGURES: {figure_nums}")
        logger.info("=" * 60)

        # Generate figures
        figure_functions = {
            1: make_figure_label_distribution,
            2: make_figure_classification_conflicts,
            3: make_figure_merger_candidates,
            4: make_figure_ha_sfs_merger_fraction,
            5: make_figure_merger_fraction_vs_mass,
            6: make_figure_merger_prob_vs_dsfs,
            7: make_figure_hamorph_distributions,
            8: make_figure_gini_m20_space,
            9: make_figure_merger_prob_vs_environment,
        }

        for fig_num in figure_nums:
            if fig_num in figure_functions:
                try:
                    figure_functions[fig_num](data, output_dir, logger)
                except Exception as e:
                    print(f'Figure {fig_num} failed: {e}')
            else:
                logger.warning(f"Unknown figure number: {fig_num}")

        logger.info("=" * 60)
        logger.info("SUCCESS")
        logger.info("=" * 60)
        print(f"\n Figure generation completed successfully!")
        print(f"   Output directory: {output_dir}")

    except Exception as e:
        logger.error(f"Error during figure generation: {e}", exc_info=True)
        print(f"\n Error: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
